<?php
/**
 * showlogsnav.
 *
 * @copyright Copyright © 2017 SalesIgniter. All rights reserved
 * @author    cristian@itwebexperts.com
 */
?>
<?php
/** @var \SalesIgniter\Debugger\Block\Showlogsnav $block */
?>
<style type="text/css">
    .salesigniter-debugger-showlogsnav-index .page-wrapper {
        height: 100%;
    }

    .salesigniter-debugger-showlogsnav-index #maincontent {
        height: 100%;
        width: 100%;
        margin: 0;
        padding: 0;
        max-width: none;
    }

    .salesigniter-debugger-showlogsnav-index .columns {
        height: 100%;
    }

    .salesigniter-debugger-showlogsnav-index .column.main {
        height: 100%;
    }
</style>
<div style="width:100%;height: 100%;">
    <div id="sitreeAll" style="float: left;width: 30%;height:100%;">
        <div style="display: block"><a target="_blank"
                                       href="<?php echo $block->getUrl('salesigniter_debugger/showlogs/index') ?>">Put
                Ajax Data into log and reset</a></div>
        <div style="display: block"><a target="_blank"
                                       href="<?php echo $block->getUrl('admin/salesigniter_debugger/showlogs/index') ?>">Put
                Ajax Admin Data into log and reset</a></div>
        <div style="display: block"><a target="_blank"
                                       href="<?php echo $block->getUrl('salesigniter_debugger/showlogs/index/delete/1') ?>">Delete
                debug</a></div>
        <div style="display: block"><a target="_blank"
                                       href="<?php echo $block->getUrl('admin/salesigniter_debugger/showlogs/index/delete/1') ?>">Delete
                Admin
                debug</a></div>
        <div style="display: block"><a target="_blank"
                                       href="<?php echo $block->getUrl('salesigniter_debugger/showlogs/index/deleteerror/1') ?>">Delete
                errors</a></div>
        <div id="sitree" style="display: block;"><?php echo $block->getTree(); ?></div>
    </div>
    <div id="sicontent" style="float: left;width:70%;height:100%;">
        <iframe style="width:100%;height:100%;"></iframe>
    </div>
    <div style="clear: both;"></div>
</div>







