<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See https://rentalbookingsoftware.com/license.html for license details.
 */
?>

<?php /** @var \SalesIgniter\Debugger\Block\CustomFrontend\Logviewer $block */ ?>

<div id="logviewer" class="logviewer" data-bind="scope:'block-logviewer'">
    <script type="text/x-magento-init">

            {
                "#logviewer": {
                    "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
                }
            }






    </script>
</div>

