<?php

namespace SalesIgniter\Debugger\Framework;

use Magento\Framework\App\Bootstrap;
use Magento\Framework\App\Filesystem\DirectoryList;

class Http extends \Magento\Framework\App\Http
{
    /**
     * @var \Whoops\Run
     */
    private $run;
    private $currentError = '';

    public function onShutdown()
    {
        $lasterror = error_get_last();
        if (in_array($lasterror['type'], [E_ERROR, E_CORE_ERROR, E_COMPILE_ERROR, E_USER_ERROR, E_RECOVERABLE_ERROR, E_CORE_WARNING, E_COMPILE_WARNING, E_PARSE])) {
            $this->writeToLogFile(new \ErrorException($lasterror['message'], $lasterror['type'], 1, $lasterror['file'], $lasterror['line']));
            //$this->run->handleException(new \RuntimeException($message));
        }
    }

    public function launch()
    {
        register_shutdown_function([&$this, 'onShutdown']);

        $this->run = new \Whoops\Run();

        //$handler = new \Whoops\Handler\PlainTextHandler;
        //$handler->setTraceFunctionArgsOutputLimit(64);
        $handler = new \Whoops\Handler\PrettyPageHandler();
        $handler->setEditor(function ($file, $line) {
            return "editor://open/?file=%file&line=%line";
        });
        $this->run->pushHandler($handler);
        //if (\Whoops\Util\Misc::isAjaxRequest()) {
        /*$areaCode = $this->_areaList->getCodeByFrontName($this->_request->getFrontName());
        $this->_state->setAreaCode($areaCode);
        area code is set in launch
        If I wanted to use some object from magento I couldn't because area code is not set and gives error
        $helperDebugger = $this->_objectManager->create('\SalesIgniter\Debugger\Helper\Data')
        $jsonHandler = new SirentJsonResponseHandler($helperDebugger);
        */
        //$jsonHandler = new SirentJsonResponseHandler();
        //$jsonHandler = new \Whoops\Handler\JsonResponseHandler();
        //$jsonHandler->addTraceToOutput(true);
        //$jsonHandler->setJsonApi(true);
        //  $this->run->pushHandler($jsonHandler);
        //}
        $returned = parent::launch();

        //if (!Debugger::isEnabled()) {
        /*Debugger::$scream = true;
        Debugger::$logSeverity = E_NOTICE | E_WARNING;
        Debugger::$strictMode = true;
        Debugger::$showBar = false;
        Debugger::$maxLength = 3000;
        Debugger::getFireLogger()->maxLength = 3000;
        Debugger::enable(Debugger::DEVELOPMENT);
        //}

        if ($this->_request->getParam('debugMessage') && $this->_request->getParam('debugMessage') !== '') {
            $helperDebugger = $this->_objectManager->create('\SalesIgniter\Debugger\Helper\Data');
            $helperDebugger->debug($this->_request->getParam('debugMessage'));
            $this->_request->setParam('debugMessage', '');
        }
        */
        // $this->run->register();
        return $returned;
    }

    public function catchException(Bootstrap $bootstrap, \Exception $exception)
    {
        if ($bootstrap->isDeveloperMode()) {
            if (\Whoops\Util\Misc::isAjaxRequest()) {
                $this->writeToLogFile($exception);
            } else {
                $this->run->writeToOutput(true);
                $this->run->handleException($exception);
            }
        }
        return parent::catchException($bootstrap, $exception); // TODO: Change the autogenerated stub
    }

    /**
     * @param \Exception $exception
     */
    public function writeToLogFile(\Exception $exception)
    {
        $this->run->writeToOutput(false);
        $this->run->allowQuit(false);
        $returnMessage = $this->run->handleException($exception);
        /** @var \SalesIgniter\Debugger\Helper\Data $helperDebugger */
        $helperDebugger = \Magento\Framework\App\ObjectManager::getInstance()->get('\SalesIgniter\Debugger\Helper\Data');
        $url = $helperDebugger->dfFileWrite(DirectoryList::MEDIA, 'errors/dieerror.html', $returnMessage);
        die('<data>Whoops! There was an error.</data>;;;' . $url);
    }
}
